sudo: false
language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3-p551
  - 2.0.0-p598
  - 2.1.0
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.1-clang
  - ruby-head
  - ruby-head-clang
  - jruby-19mode
  - jruby-head
notifications:
  recipients:
    - thomas@slash7.com